DROP DATABASE demo2023;
CREATE DATABASE demo2023;

CREATE TABLE jokes(
    id INTEGER auto_increment not null,
    description VARCHAR(150)  NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	disabled_at DATETIME,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;